In [2]:
%pip install psycopg2-binary sqlalchemy pandas

Requirement already satisfied: psycopg2-binary in c:\users\alexa\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\alexa\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pandas in c:\users\alexa\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: greenlet>=1 in c:\users\alexa\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\alexa\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\alexa\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\alexa\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\alexa\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\alexa\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\alexa\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
from dotenv import load_dotenv
import os

from sqlalchemy import create_engine, text, literal
import pandas as pd

In [2]:
load_dotenv()
password = os.getenv("DB_PASSWORD")

### Loading all the data...

In [3]:
df_episodes = pd.read_csv("Episodes.csv")
df_bakers = pd.read_csv("Bakers.csv")
df_challenges = pd.read_csv("ChallengeBakes.csv")
df_outcomes = pd.read_csv("Outcomes.csv")
df_seasons = pd.read_csv("Seasons.csv")

In [4]:
engine = create_engine(
    f"postgresql://postgres:{password}@localhost:5432/GB_bakeoff"
)

In [10]:
df_episodes.to_sql(
    "episodes",
    engine,
    if_exists="replace",
    index=False
)

df_bakers.to_sql(
    "bakers",
    engine,
    if_exists="replace",
    index=False
)

df_challenges.to_sql(
    "challenges",
    engine,
    if_exists="replace",
    index=False
)

df_outcomes.to_sql(
    "outcomes",
    engine,
    if_exists="replace",
    index=False
)

df_seasons.to_sql(
    "seasons",
    engine,
    if_exists="replace",
    index=False
)

56

## Data Exploration

In [42]:
pd.read_sql("SELECT * FROM episodes", engine)

,Airdate,Season,Episode,Theme,Signature,Signature Time (min),Technical,Technical Time (min),Showstopper,Showstopper Time (min),MyRating (out of 10),MyViewership
0,8/17/2010,1,1,Cake,Cake,180.0,Victoria Sandwich,NaN,Chocolate Celebration Cake,NaN,8.0,8.57
1,8/24/2010,1,2,Biscuit,Personality Biscuits,120.0,Scones,60.0,"Meringue, Choux, and Macaron Petits Fours",240.0,7.8,11.14
2,8/31/2010,1,3,Bread,Signature Bread,210.0,Cob,150.0,12 Sweet and 12 Savoury Rolls,360.0,7.9,11.47
3,9/7/2010,1,4,Pudding,Classic Pudding,150.0,Mini Hot Lemon Soufflés,40.0,"Crumble, Bread, & Suet Puddings",300.0,7.7,11.03
4,9/14/2010,1,5,Pastry,Savoury Pie,150.0,Cornish Pasties,90.0,Savory Canapés and Sweet Tartlets,300.0,7.8,11.93
...,...,...,...,...,...,...,...,...,...,...,...,...
129,10/31/2023,14,6,Botanical,12 Individual Spiced Buns,165.0,Lemon and Thyme Drizzle Cake,90.0,Floral Dessert,240.0,7.8,33.66
130,11/7/2023,14,7,Desserts,8 Creme Caramels,165.0,Orange and Ginger Treacle Puddings,90.0,Meringue Bombe,NaN,7.9,34.69
131,11/14/2023,14,8,Party,12 Sausage Rolls,150.0,Caterpiller Cake,150.0,Anything But Beige Buffet,270.0,8.1,39.12
132,11/21/2023,14,9,Patisserie,24 Financiers,120.0,Tart aux Pommes,150.0,Millefoglie,240.0,8.0,38.59
133,11/28/2023,14,10,Final,8 Éclairs,135.0,9 Lardy Cake Slices,180.0,Tiered Celebration Cake,270.0,8.5,44.87

In [48]:
query = text('SELECT * FROM COBE ORDER BY "Season", "Episode"')
pd.read_sql(query, engine)

,Baker,Season,SeasonEpisode,Episode,Signature Bake,Rank in Technical,Showstopper,Status,Star Baker,Did well,...,At risk,Eliminated,Absent,Handshake,Age,Gender,MyRating (out of 10),MyViewership,Theme,Airdate
0,Lea,1,s1e1,1,Cranberry and Pistachio Cake with Orange Flowe...,10.0,Raspberries and Cream-filled Chocolate Cake wi...,Eliminated,0,0,...,0,1,0,0,51,F,8.0,8.57,Cake,8/17/2010
1,Jasminder,1,s1e1,1,Fresh Mango and Passion Fruit Hummingbird Cake,NaN,None,Safe,0,0,...,0,0,0,0,45,F,8.0,8.57,Cake,8/17/2010
2,Jonathan,1,s1e1,1,Carrot Cake with Lime and Cream Cheese Icing,9.0,Three Tiered White and Dark Chocolate with Alm...,Safe,0,0,...,0,0,0,0,25,M,8.0,8.57,Cake,8/17/2010
3,DavidC,1,s1e1,1,Chocolate Orange Cake,3.0,Black Forest Floor Gateau with Moulded Chocola...,At risk,0,0,...,1,0,0,0,31,M,8.0,8.57,Cake,8/17/2010
4,Annetha,1,s1e1,1,Light Jamaican Black Cake with Strawberries an...,2.0,"Red, White & Blue Chocolate Cake with Cigarell...",Did well,0,1,...,0,0,0,0,30,F,8.0,8.57,Cake,8/17/2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
956,DanH,14,s14e8,8,Dumplings in Disguise Sausage Rolls,5.0,Prehistoric Party Poopers Buffet,At risk,0,0,...,1,0,0,0,42,M,8.1,39.12,Party,11/14/2023
957,Tasha,14,s14e9,9,Fancy Fruit & Nut Financiers,4.0,Mango Mojito Millefoglie,Eliminated,0,0,...,0,1,0,0,27,F,8.0,38.59,Patisserie,11/21/2023
958,DanH,14,s14e9,9,Fancy Financiers,3.0,Hypersonic Millefoglie,Did well,0,1,...,0,0,0,1,42,M,8.0,38.59,Patisserie,11/21/2023
959,Matty,14,s14e9,9,Pick Me Up Financiers,2.0,Taste of Italy Millefoglie,At risk,0,0,...,1,0,0,0,28,M,8.0,38.59,Patisserie,11/21/2023
960,Josh,14,s14e9,9,Perfect Pudding Financiers,1.0,"Lemon, Blackberry, & Blackcurrant Millefoglie",Star Baker,1,0,...,0,0,0,0,27,M,8.0,38.59,Patisserie,11/21/2023

In [7]:
query = text('SELECT * FROM challenges c WHERE c."SeasonEpisode" LIKE :season10 ORDER BY c."SeasonEpisode"')
pd.read_sql(query, engine, params={"season10": "%s10%"})

,Season,Episode,Baker,SeasonEpisode,Signature Bake,Rank in Technical,Showstopper,Status
0,10,1,Rosie,s10e1,Spicy Chai Loaf,2.0,Magical Jungle Cake,Safe
1,10,1,Henry,s10e1,Wood Street Cake,1.0,Secret Woodland Cake,Safe
2,10,1,MichaelC,s10e1,Cup of Chai Cake,11.0,Treasure Chest Cake,Safe
3,10,1,Priya,s10e1,Sunshine Fruit Cake,7.0,Once Upon a Time Cake,Safe
4,10,1,Helena,s10e1,Fruit Bat Cake,12.0,Away with the Fairies Cake,Safe
...,...,...,...,...,...,...,...,...
75,10,8,Steph,s10e8,Caramelised Onion & Goat's Cheese Tarte Tatin,4.0,Curried Chickpea & Potato Carousel Pie,Star Baker
76,10,9,Rosie,s10e9,"Lemon, Raspberry & Mint Domed Tarts",1.0,Time with Family,Eliminated
77,10,9,DavidA,s10e9,Aperitif Domed Tarts,2.0,Greenhouse Growing Moss,At risk
78,10,9,Alice,s10e9,"Mocha, Hazelnut & Orange Domed Tarts",4.0,Save Our Oceans,Star Baker
79,10,9,Steph,s10e9,"Raspberry, Lemon & White Chocolate Domed Tarts",3.0,A Night at the Opera,Did well

### Making a new table with combined Challenge, Outcome, Baker and Episode data... also removing some unnecessary columns

In [47]:
query = text('CREATE TABLE COB AS SELECT * FROM challenges c NATURAL JOIN outcomes o NATURAL JOIN bakers b')
query2 = text('ALTER TABLE COB DROP COLUMN "Image Link"')
query3 = text('CREATE TABLE COBE AS SELECT cob.*, e."MyRating (out of 10)", e."MyViewership", e."Theme", e."Airdate" FROM COB cob LEFT JOIN episodes e USING ("Season", "Episode")')

with engine.begin() as conn:
    conn.execute(query)
    conn.execute(query2)
    conn.execute(query3)

## Making some more tables - Ratings and Viewership by Episode, Season and Theme

In [51]:
query_season_views = text('Select "Season", AVG("MyRating (out of 10)") as "Avg Rating (out of 10)", AVG("MyViewership") as "Avg Viewership" From COBE GROUP BY "Season" ORDER BY "Season"')
pd.read_sql(query_season_views, engine)

    Season  Avg Rating (out of 10)  Avg Viewership
0        1                7.863636       10.500303
1        2                7.850877       13.003158
2        3                8.134247       16.940959
3        4                7.936000       24.073733
4        5                8.075714       33.854000
5        6                7.936111       43.564306
6        7                7.962500       47.785139
7        8                7.630556       32.182639
8        9                7.500000       33.301806
9       10                7.527273       35.258052
10      11                7.341667       38.438194
11      12                7.418056       32.839861
12      13                7.435211       28.321972
13      14                7.928767       32.614658

In [52]:
query_episode_views = text('Select "Episode", AVG("MyRating (out of 10)") as "Avg Rating (out of 10)", AVG("MyViewership") as "Avg Viewership" From COBE GROUP BY "Episode" ORDER BY "Episode"')
pd.read_sql(query_episode_views, engine)

   Episode  Avg Rating (out of 10)  Avg Viewership
0        1                7.841667       30.226786
1        2                7.821569       30.341895
2        3                7.772794       30.753088
3        4                7.647541       30.748525
4        5                7.664220       30.552294
5        6                7.725000       32.125795
6        7                7.611688       32.623377
7        8                7.808333       33.814167
8        9                7.716667       34.960000

In [53]:
query_theme_views = text('Select "Theme", AVG("MyRating (out of 10)") as "Avg Rating (out of 10)", AVG("MyViewership") as "Avg Viewership" From COBE GROUP BY "Theme" ORDER BY "Avg Viewership" DESC, "Avg Rating (out of 10)" DESC')
pd.read_sql(query_theme_views, engine)

                      Theme  Avg Rating (out of 10)  Avg Viewership
0                     Tudor                8.100000       47.920000
1                    Batter                7.700000       45.770000
2                 Victorian                7.700000       43.210000
3                 Botanical                7.900000       40.970000
4                  The '80s                6.800000       40.360000
5                   Dessert                8.250000       40.180000
6                     Party                8.100000       39.120000
7                Patisserie                8.000000       38.590000
8                  Japanese                7.300000       38.120000
9                 Chocolate                7.727273       37.135455
10  Alternative Ingredients                7.884615       36.749231
11           European Cakes                7.900000       36.160000
12                    Dairy                7.600000       35.270000
13           Advanced Dough                8.500000       34.820000
14                   Danish                7.500000       34.590000
15     The Roaring Twenties                6.800000       34.380000
16                Free-from                7.400000       34.340000
17                   Pastry                7.702532       33.850380
18                 Festival                7.700000       33.420000
19               Pâtisserie                7.662222       33.363556
20                    Vegan                7.600000       32.920000
21                  Biscuit                7.710656       32.342705
22                  Caramel                7.560000       32.234000
23                  Italian                7.300000       32.170000
24                   German                7.500000       31.720000
25          Forgotten bakes                7.800000       31.230000
26                    Spice                7.600000       30.900000
27                    Bread                7.832609       30.524638
28                     Cake                7.829940       30.141737
29                 Desserts                7.720270       29.371081
30                 Biscuits                8.100000       29.270000
31                  Mexican                6.600000       29.090000
32           Pies and Tarts                7.743750       28.625625
33                Halloween                7.300000       27.420000
34                  Custard                7.000000       27.330000
35              French Week                7.800000       26.890000
36   Biscuits and Traybakes                7.900000       22.820000
37              Sweet Dough                8.000000       21.045000
38                  Pudding                7.755000       20.586500
39                     Pies                8.000000       15.399333
40                    Tarts                7.952381       14.928571

In [54]:
query_season_views = text('CREATE TABLE "Season Views" AS Select "Season", AVG("MyRating (out of 10)") as "Avg Rating (out of 10)", AVG("MyViewership") as "Avg Viewership" From COBE GROUP BY "Season"')
query_episode_views = text('CREATE TABLE "Episode Views" AS Select "Episode", AVG("MyRating (out of 10)") as "Avg Rating (out of 10)", AVG("MyViewership") as "Avg Viewership" From COBE GROUP BY "Episode"')
query_theme_views = text('CREATE TABLE "Theme Views" AS Select "Theme", AVG("MyRating (out of 10)") as "Avg Rating (out of 10)", AVG("MyViewership") as "Avg Viewership" From COBE GROUP BY "Theme"')

with engine.begin() as conn:
    conn.execute(query_season_views)
    conn.execute(query_episode_views)
    conn.execute(query_theme_views)

#### Investigating the Tudor Theme as it has the highest average viewership

In [48]:
query = text("""Select "SeasonEpisode", "Baker", "Theme", "Signature Bake", "Showstopper" From COBE WHERE "Theme"='Tudor'""")
pd.read_sql(query, engine)

,SeasonEpisode,Baker,Theme,Signature Bake,Showstopper
0,s7e8,Andrew,Tudor,Da Vinci Inspired Geared Pies,Jousting Knights Marchpane
1,s7e8,Benjamina,Tudor,Mexican Adventure,Tudor Garden
2,s7e8,Selasi,Tudor,Bouquet of Flowers,Fruity Tudor Marchpane
3,s7e8,Jane,Tudor,Tudor Rose Pies,Swans
4,s7e8,Candice,Tudor,Cheesy Cheeky Fish Pies,Peacock

### More tables - star bakers info, season winners, networks

In [72]:
query_star_baker = text('CREATE TABLE "bakers2" AS SELECT "Baker", "Age", "Gender", "Season", SUM(CASE WHEN "Star Baker" = 1 THEN 1 ELSE 0 END) AS "Times Star Baker" FROM COBE GROUP BY "Baker", "Season", "Age", "Gender" ORDER BY "Times Star Baker" DESC, "Season", "Baker";')
# pd.read_sql(query_star_baker, engine)

with engine.begin() as conn:
    conn.execute(query_star_baker)

In [84]:
query_winners = text('CREATE TABLE winners AS SELECT DISTINCT s."Winner", b."Season", b."Age", b."Gender", b."Times Star Baker", sv."Avg Rating (out of 10)", sv."Avg Viewership" FROM bakers2 b NATURAL JOIN "Season Views" sv JOIN seasons s ON b."Baker"=s."Winner" AND b."Season"=s."Season";')

with engine.begin() as conn:
    conn.execute(query_winners)

In [87]:
query_network = text("""CREATE TABLE network AS SELECT s."Season", s."Network", s."PBS Season", s."Netflix Collection", s."Roku Season", sv."Avg Rating (out of 10)", sv."Avg Viewership" FROM seasons s NATURAL JOIN "Season Views" sv;""")

with engine.begin() as conn:
    conn.execute(query_network)

### Adding the average technical rank of bakers in the bakers2 and winners table

In [43]:
q1_winners = text('ALTER TABLE winners ADD "Avg Technical Rank" FLOAT;')
q2_winners = text("""UPDATE winners w
SET "Avg Technical Rank" = t."Avg Technical Rank"
FROM (
SELECT c."Baker", AVG(c."Rank in Technical") as "Avg Technical Rank" FROM COBE c GROUP BY "Baker"
) as t
WHERE t."Baker" = w."Winner"
;""")

with engine.begin() as conn:
    conn.execute(q1_winners)
    conn.execute(q2_winners)

In [45]:
q1_bakers = text('ALTER TABLE bakers2 ADD "Avg Technical Rank" FLOAT;')
q2_bakers = text("""UPDATE bakers2 b
SET "Avg Technical Rank" = t."Avg Technical Rank"
FROM (
SELECT c."Baker", AVG(c."Rank in Technical") as "Avg Technical Rank" FROM COBE c GROUP BY "Baker"
) as t
WHERE t."Baker" = b."Baker"
;""")

with engine.begin() as conn:
    conn.execute(q1_bakers)
    conn.execute(q2_bakers)

### Adding the average technical rank for each episode, for each season, and for each theme

In [60]:
query = text("""Select "Baker", "Theme", "Season", "Episode", "Rank in Technical" from COBE WHERE "Season" = 10;""")
pd.read_sql(query, engine)

     Baker       Theme  Season  Episode  Rank in Technical
0    Steph        Cake      10        1                3.0
1    Priya        Cake      10        1                7.0
2   DavidA        Cake      10        1               10.0
3    Alice        Cake      10        1                5.0
4    Jamie        Cake      10        1               13.0
..     ...         ...     ...      ...                ...
72  DavidA      Pastry      10        8                1.0
73   Alice  Pâtisserie      10        9                4.0
74   Rosie  Pâtisserie      10        9                1.0
75   Steph  Pâtisserie      10        9                3.0
76  DavidA  Pâtisserie      10        9                2.0

[77 rows x 5 columns]

In [57]:
q1_themes = text('ALTER TABLE "Theme Views" ADD "Avg Technical Rank" FLOAT;')
q2_themes = text("""UPDATE "Theme Views" th
SET "Avg Technical Rank" = t."Avg Technical Rank"
FROM (
SELECT c."Theme", AVG(c."Rank in Technical") as "Avg Technical Rank" FROM COBE c GROUP BY "Theme"
) as t
WHERE t."Theme" = th."Theme"
;""")

with engine.begin() as conn:
    conn.execute(q1_themes)
    conn.execute(q2_themes)

In [58]:
q1_seasons = text('ALTER TABLE "Season Views" ADD "Avg Technical Rank" FLOAT;')
q2_seasons = text("""UPDATE "Season Views" sv
SET "Avg Technical Rank" = t."Avg Technical Rank"
FROM (
SELECT c."Season", AVG(c."Rank in Technical") as "Avg Technical Rank" FROM COBE c GROUP BY "Season"
) as t
WHERE t."Season" = sv."Season"
;""")

with engine.begin() as conn:
    conn.execute(q1_seasons)
    conn.execute(q2_seasons)

In [59]:
q1_episodes = text('ALTER TABLE "Episode Views" ADD "Avg Technical Rank" FLOAT;')
q2_episodes = text("""UPDATE "Episode Views" ep
SET "Avg Technical Rank" = t."Avg Technical Rank"
FROM (
SELECT c."Episode", AVG(c."Rank in Technical") as "Avg Technical Rank" FROM COBE c GROUP BY "Episode"
) as t
WHERE t."Episode" = ep."Episode"
;""")

with engine.begin() as conn:
    conn.execute(q1_episodes)
    conn.execute(q2_episodes)

In [61]:
q1_all_episodes = text('ALTER TABLE episodes ADD "Avg Technical Rank" FLOAT;')
q2_all_episodes = text("""UPDATE episodes ep
SET "Avg Technical Rank" = t."Avg Technical Rank"
FROM (
SELECT c."Episode", c."Season", AVG(c."Rank in Technical") as "Avg Technical Rank" FROM COBE c GROUP BY "Season", "Episode"
) as t
WHERE t."Episode" = ep."Episode" AND t."Season" = ep."Season"
;""")

with engine.begin() as conn:
    conn.execute(q1_all_episodes)
    conn.execute(q2_all_episodes)

In [11]:
q = text("""select MAX("Rank in Technical"), MIN("Rank in Technical"), AVG("Rank in Technical") from COBE;""")
pd.read_sql(q, engine)

    max  min       avg
0  13.0  1.0  4.942469

In [13]:
q = text("""select * from "Episode Views" ORDER BY "Avg Technical Rank";""")
pd.read_sql(q, engine)

   Episode  Avg Rating (out of 10)  Avg Viewership  Avg Technical Rank
0        9                7.716667       34.960000            2.500000
1        8                7.808333       33.814167            3.000000
2        7                7.611688       32.623377            3.493506
3        6                7.725000       32.125795            3.909091
4        5                7.664220       30.552294            4.486239
5        4                7.647541       30.748525            4.900826
6        3                7.772794       30.753088            5.433824
7        2                7.821569       30.341895            6.000000
8        1                7.841667       30.226786            6.542683

## Power BI graphs:

### -Viewership trends over seasons

### -Viewership trends over episode #s (does final episode get better viewership than like episode 1 for example?)

### -Viewership/Rating trends over time

### -Viewership may be affected by the platform (PBS/Netflix/Roku) AND/OR Network (BBC Two / Channel 4)

### -Viewership for certain themes

### -Star baker counts for winners - see if that aligns with viewership/ratings (higher # of star baker for the winner affects viewership/ratings?)